### ISSUE TITLE
ImportError: No module named importlib with behave on Python 2.6

### ISSUE THREAD

**Issue by eliangcs** [dbcli/vcli#23]
Seems like the latest `behave` (1.2.5) does not work with Python 2.6 well:
https://travis-ci.org/dbcli/vcli/jobs/87407092

@amjith I don't see pgcli had this issue. Did you guys ever run into this problem?

**Comment by amjith** [comment]
Paging @j-bennet.

**Comment by j-bennet** [comment]
That's right, we pinned it in pgcli. I'll do that.

https://github.com/dbcli/pgcli/blob/master/requirements-dev.txt#L5

**Comment by eliangcs** [comment]
Fixed in #24.
