### ISSUE TITLE
explain does not show output

### ISSUE THREAD

**Issue by keatsfonam** [dbcli/vcli#42]
I can't seem to get any output for explain or any of the variations - not sure if this is a known issue or not:

=> explain select 1;
Time: 0.038s
=>
=> explain local verbose select 1;
Time: 0.046s

There also seems to be the same issue with the PROFILE command

**Comment by eliangcs** [comment]
The EXPLAIN issue has been fixed in the master branch. I'll fix PROFILE issue in another PR. Thanks for reporting!

**Comment by eliangcs** [comment]
Fixed in the master branch.
